// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osafqugxjkvnbpobjzyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zYWZxdWd4amt2bmJwb2JqenlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTIxNDksImV4cCI6MjA2MTY4ODE0OX0.KMDNS4AglyS8hFVTH2rRK5Ca3bQ7vqaGefIdfcjBZW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);